/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StartledLlama (https://sketchfab.com/StartledLlama)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sustainable-globe-54998d9b1d3445b3b9969609353edf18
Title: Sustainable Globe
*/

import {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export function Planet(props) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/sustainable_globe.glb')
    // const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" scale={0.5} rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="16d0a7f9f014419aaf219e7cbb73ce4ffbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="whater" rotation={[-1.507, 0.055, -1.543]} scale={100}>
                                    <mesh
                                        name="whater_Water_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.whater_Water_0.geometry}
                                        material={materials.Water}
                                    />
                                    <group name="Land">
                                        <mesh
                                            name="Land_Earth_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Land_Earth_0.geometry}
                                            material={materials.Earth}
                                        />
                                    </group>
                                    <group
                                        name="Cylinder003"
                                        position={[0.669, -0.088, 0.832]}
                                        rotation={[0.337, 0.437, 0.628]}
                                        scale={0.046}>
                                        <mesh
                                            name="Cylinder003__0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder003__0.geometry}
                                            material={materials['Cylinder.003__0']}
                                        />
                                        <group
                                            name="Cube003"
                                            position={[0.018, -0.89, 11.506]}
                                            rotation={[0, -0.101, 0]}
                                            scale={[0.228, 0.078, 0.228]}>
                                            <mesh
                                                name="Cube003__0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cube003__0.geometry}
                                                material={materials['Cylinder.003__0']}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Cylinder004"
                                        position={[-0.833, -0.501, 0.536]}
                                        rotation={[1.103, -0.779, -0.598]}
                                        scale={0.046}>
                                        <mesh
                                            name="Cylinder004__0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder004__0.geometry}
                                            material={materials['Cylinder.003__0']}
                                        />
                                        <group
                                            name="Cube004"
                                            position={[0.018, -0.89, 11.506]}
                                            rotation={[0, -0.101, 0]}
                                            scale={[0.228, 0.078, 0.228]}>
                                            <mesh
                                                name="Cube004__0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cube004__0.geometry}
                                                material={materials['Cylinder.003__0']}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Cylinder005"
                                        position={[0.49, -0.949, 0.052]}
                                        rotation={[1.25, 0.528, -0.385]}
                                        scale={0.046}>
                                        <mesh
                                            name="Cylinder005__0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder005__0.geometry}
                                            material={materials['Cylinder.003__0']}
                                        />
                                        <group
                                            name="Cube005"
                                            position={[0.018, -0.89, 11.506]}
                                            rotation={[0, -0.101, 0]}
                                            scale={[0.228, 0.078, 0.228]}>
                                            <mesh
                                                name="Cube005__0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cube005__0.geometry}
                                                material={materials['Cylinder.003__0']}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Cylinder007"
                                        position={[-0.404, 0.946, 0.462]}
                                        rotation={[-1.522, -0.259, 2.294]}
                                        scale={0.046}>
                                        <mesh
                                            name="Cylinder007__0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder007__0.geometry}
                                            material={materials['Cylinder.003__0']}
                                        />
                                        <group
                                            name="Cube007"
                                            position={[0.018, -0.89, 11.506]}
                                            rotation={[0, -0.101, 0]}
                                            scale={[0.228, 0.078, 0.228]}>
                                            <mesh
                                                name="Cube007__0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cube007__0.geometry}
                                                material={materials['Cylinder.003__0']}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Cylinder008"
                                        position={[0.199, 0.372, -0.979]}
                                        rotation={[-2.466, 0.115, -0.768]}
                                        scale={0.046}>
                                        <mesh
                                            name="Cylinder008__0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cylinder008__0.geometry}
                                            material={materials['Cylinder.003__0']}
                                        />
                                        <group
                                            name="Cube008"
                                            position={[0.018, -0.89, 11.506]}
                                            rotation={[0, -0.101, 0]}
                                            scale={[0.228, 0.078, 0.228]}>
                                            <mesh
                                                name="Cube008__0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.Cube008__0.geometry}
                                                material={materials['Cylinder.003__0']}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Cube011"
                                        position={[0.931, -0.296, 0.408]}
                                        rotation={[0.877, 1.027, -0.517]}>
                                        <mesh
                                            name="Cube011_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube011_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube011_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube011_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube011_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube011_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube010"
                                        position={[-0.114, 0.09, 1.059]}
                                        rotation={[-0.056, -0.16, 0.689]}>
                                        <mesh
                                            name="Cube010_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube010_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube010_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube010_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube010_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube010_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube012"
                                        position={[-0.157, -1.044, 0.103]}
                                        rotation={[1.295, -0.205, 2.378]}>
                                        <mesh
                                            name="Cube012_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube012_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube012_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube012_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube012_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube012_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube017"
                                        position={[-0.844, -0.04, 0.702]}
                                        rotation={[-0.307, -0.9, 0.655]}>
                                        <mesh
                                            name="Cube017_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube017_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube017_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube017_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube017_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube017_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube018"
                                        position={[-0.653, 0.85, -0.106]}
                                        rotation={[-1.805, -0.34, 1.795]}>
                                        <mesh
                                            name="Cube018_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube018_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube018_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube018_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube018_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube018_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube019"
                                        position={[-0.084, -0.082, -1.071]}
                                        rotation={[3.096, 0.059, -1.835]}>
                                        <mesh
                                            name="Cube019_Material003_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube019_Material003_0.geometry}
                                            material={materials['Material.003']}
                                        />
                                        <mesh
                                            name="Cube019_Material002_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube019_Material002_0.geometry}
                                            material={materials['Material.002']}
                                        />
                                        <mesh
                                            name="Cube019_Material001_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube019_Material001_0.geometry}
                                            material={materials['Material.001']}
                                        />
                                    </group>
                                    <group
                                        name="Cube001"
                                        position={[0.019, -0.662, 0.826]}
                                        rotation={[0.773, 0.018, -0.266]}
                                        scale={0.01}>
                                        <mesh
                                            name="Cube001_tre_1_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_1"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_1.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_2"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_2.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_3"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_3.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_4"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_4.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_5"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_5.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_6"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_6.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_7"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_7.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_8"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_8.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_9"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_9.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_10"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_10.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_11"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_11.geometry}
                                            material={materials.tre_1}
                                        />
                                        <mesh
                                            name="Cube001_tre_1_0_12"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Cube001_tre_1_0_12.geometry}
                                            material={materials.tre_1}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="Area"
                                    position={[136.244, 166.129, -325.308]}
                                    rotation={[2.653, -1.178, -2.292]}
                                    scale={100}>
                                    <group name="Object_67" rotation={[Math.PI / 2, 0, 0]}>
                                        <group name="Object_68"/>
                                    </group>
                                </group>
                                <group
                                    name="Sphere002"
                                    position={[-2455.555, -3.113, -4.579]}
                                    rotation={[0.263, 0.023, -1.577]}
                                    scale={5.782}>
                                    <mesh
                                        name="Sphere002__0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Sphere002__0.geometry}
                                        material={materials['Cylinder.003__0']}
                                    />
                                </group>
                                <group name="whater001" rotation={[-1.507, 0.055, -1.543]} scale={97.685}>
                                    <mesh
                                        name="whater001__0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.whater001__0.geometry}
                                        material={materials['Cylinder.003__0']}
                                    />
                                </group>
                                <group
                                    name="Cube030"
                                    position={[-1.495, 29.726, -99.612]}
                                    rotation={[0.362, 0.03, 0.933]}
                                    scale={[-1.455, -0.696, -0.696]}>
                                    <mesh
                                        name="Cube030_Material006_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube030_Material006_0.geometry}
                                        material={materials['Material.006']}
                                    />
                                    <mesh
                                        name="Cube030_Material004_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube030_Material004_0.geometry}
                                        material={materials['Material.004']}
                                    />
                                    <mesh
                                        name="Cube030_Material005_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube030_Material005_0.geometry}
                                        material={materials['Material.005']}
                                    />
                                    <mesh
                                        name="Cube030_Material007_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube030_Material007_0.geometry}
                                        material={materials['Material.007']}
                                    />
                                    <mesh
                                        name="Cube030_Material008_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Cube030_Material008_0.geometry}
                                        material={materials['Material.008']}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/sustainable_globe.glb')
